### ISSUE TITLE
Asus P4540UQ Notebook and UAD Realtek drivers

### ISSUE THREAD

**Issue by Kherby** [CHEF-KOCH/GamingTweaks#1]
I would realy like to test the lastest driver audio driver (6.0.1.8480 WHQL) with my Asus Pro P4540UQ Notebook but the install routine will tell me that it doesn't found a compatible driver :/
The latest driver from Asus for my Notebook model is Version 6.0.1.8308.
My Realtek Audio Hardware ID:                                                HDAUDIO\FUNC_01&VEN_10EC&DEV_0255&SUBSYS_10431650&REV_1000

I'm using windows 10 1803 and i often hear a little cracking sound when the Audio is starting to play, it's really annoying and I think it's related to the used driver...

Which driver can/should i use ?

**Comment by CHEF-KOCH** [comment]
Dunno, Google doesn't found any corresponding result entry, do you know or have checked which codec/chip your mainboard manufacturer has written down on the manual/specification page?

I recently had a similar issue with my old HP laptop which is also not UAD ready but I could override the driver and could install another one which officially _doesn't work_. So maybe try to override the warning, by uninstalling the old driver, reboot and try to update your driver manually via device manager and then confirm you like to use the 'wrong' driver when you get the warning.

I can't really help cause I don't find any Codec/Chip to that hardware ID you gave me, maybe post the exact mainboard name including a number and I can check which chip you have and then I can say more.

However, you always can use the _old_ HDA driver but I not really recommend them anymore cause they install other bullshit which no one really needs and they're not optimal optimized for newer Windows versions.

**Comment by Kherby** [comment]
Thanks for your help !! I do appreciate that a lot ! :)

I was able to install **8470_FF00_PG467_Win10_RS1_RS2_RS3_RS4_Win7_WHQL** via the normal setup.exe...
And it's basicly the first Realtek package where the HD Audio-Manager works out of the Box for me !!!
Btw, there is a Asus.txt file under C:\Program Files\Realtek\Audio\Drivers which contains "P4540UQ_1650_ICEP_MICEQ02".
I've also deinstalled ICE before the driver update and after driver update i've installed it again as it really improves the Audio quality when listening to music.
`http://dlcdnet.asus.com/pub/ASUS/nb/Apps_for_Win10/ICEsound/ICEsound_Win10_64_VER10581.zip`

Sadly i can still hear the crackle sounds, so maybe my speakers are just broken...
The weird thing is that the crackle sound only appears at the UAC prompt (when i start a program) or at the beginning of the speaker test, but not always, it's kinda random...
When i listen to music or watch videos aso the speakers are working just fine, the crackle sound only occurs at the beginning of small sound files (windows sound files for example) and when there is no other background sound active !
My Notebook was send to a Asus repair center once (faulty Touchpad),  so maybe they have damaged the speakers in the repair process... :/

Btw, my sound chip is: Realtek ALC255
And with HWiNFO64 i get the following informations:
```
Audio Adapter: Intel Kaby Lake-U/Y PCH - High Definition Audio Controller
Audio Controller Hardware ID: PCI\VEN_8086&DEV_9D71&SUBSYS_16501043&REV_21
Audio Codec Hardware ID: HDAUDIO\FUNC_01&VEN_10EC&DEV_0255&SUBSYS_00000000
DeviceInstanceId: HDAUDIO\FUNC_01&VEN_10EC&DEV_0255&SUBSYS_10431650&REV_1000\4&40278EB&0&0001
```

I'll give it a try with 8475 but i would realy like to test 6.0.1.8480 WHQL because you mentioned it's the "First Driver which fully addresses all reported Audio related issue on Windows 10 RS4"...
And if i understand it correctly the Asus package also contains ICE.

**Comment by Kherby** [comment]
I've successfully installed 8475 but the crackle is still present...
I kinda think now that it's not driver related and i have to send my Notebook to Asus once again...
It will be a pain to backup all my stuff and i'm not even sure if they will fix it as it's kinda random...
Anyway my Touchpad is also behaving quite strange again (mouse cursor jumps around most of the time when i use the double Tap to click function).

This Notebook is really driving me crazy ! :/

**Comment by CHEF-KOCH** [comment]
The ALC Codec/Chip is definitely UAD ready but seems Asus have forgotten to add the ID into the inf file. ICE is definitely not a part of any UAD driver and is usually replaced with Sonics Spartial sound feature but that's also not (yet?) included into the Asus package so you have to manually install it in order to activate it.

You (for now) can only override the driver manually or send the notebook back to Asus, I mean it's not an old one and there shouldn't be any crackling no matter which driver they officially provide. It also can be a throttling issue, which I believe which is coming these days from the chipset, cause the GPU and or the CPU gets automatically limited on Kaby-Lake boards if the CPU/or GPU reaches a specific temp or state. I know setting windows to 'full power' in the energy management might partially 'fixes' this but also causes more battery drain when opening the normal apps like Chrome etc.

**Comment by Kherby** [comment]
Yea, it's really a weird issue !

It shouldn't be a throttling problem as i always watch my temps and they are normaly not over 55C and there is no Thermal Throttling happening.
I can also undervolt my CPU with -0.092v, same goes for the cache and the iGPU so the Notebook holds the 3.1GHz permamently, even under full load (stresstest, benchmark, ~max 70C).
Asus has set the Power Boost Max to 25W and with undervolting there is no Power Limit Throttling happening and the device is also very quiet under normal usage.
Overall a nice Notebook but the problem with the Sound and Touchpad makes me quite mad sometimes !!
I still have ~1 year Warranty so i might send it back to Asus, it's just a pain to backup everything (+ License related problems if they change the hardware).

HwMonitor: https://imgur.com/6gh6CoA

Btw, im using foobar2000 since a few years allready but i haven't messed with the EQ much and ICE with the Asus Notebook works quite well for me (youtube, VLC, Foobar)...

Thanks for your time !! :)

**Comment by Kherby** [comment]
https://github.com/CHEF-KOCH/regtweaks/blob/master/Win%2010/RS%204%20(1803)/Audio%20crackling%20fix%20%5BTEST!%5D/Tweaked.reg

Could this possibly fix my problem with the crackling ? I'll give it a try... ;)

**Comment by CHEF-KOCH** [comment]
Even if that would solve somehow the crackling issue you still have to solve the problem that Asus hasn't updated their TouchPad Driver for over one year.

**Comment by Kherby** [comment]
True words, they haven't even updated the BIOS Version lately and the latest BIOS isn't even patched against Spectre! 
 (P4540UQ.305, BIOS Release Date: 06/30/2017)
Asus support is really not the best when it comes down to updates and repairs!

The crackle problem is still present with the registry tweak.
And i think the Touchpad is faulty hardware wise and it's not a driver problem.
Without the Asus driver the problem is still present and the "jumping mouse cursor problem" even occurs when i use the "double tap to click" function in BIOS...

On the repair paper they have stated that the touchpad part was completely changed but for some reason i think that they haven't changed anything as the problem was never completely fixed at any point. 
I'm pretty much an Idiot for not sending it back directly but at that point i needed a device to work with!

I can't even test a brand new device of the same model to make sure it's just "my device" having these kind of problems as the model isn't available anymore (I can't buy it anymore)...
That's why i think Asus isn't going to fix my touchpad and sound, even if my device is still under warranty.

It's so frustrating and i already thinking about buying a new Notebook with i5-8.gen CPU but i'm not sure for which model and brand i should go this time... :/

**Comment by CHEF-KOCH** [comment]
Maybe you should go ahead make a cut and also think about switching to AMD. Intel handled the entire Spectre & Meltdown story really badly, they lied and tried to fool people with 'oh it's not so urgent etc' marketing rhetoric. They only did something after pressure from the Linux community and other brands.

There coming some sweet AMD Zen2+ notebooks, during the next Christmas season. Maybe try to get your money back and switch to HP there also not the best but at least my old HP 250 G5 Laptop still gets Bios and other updates.

I also definitly switch to AMD on all my systems over the next 8 months.

**Comment by Kherby** [comment]
I was actually about to buy a HP Probook 450 G5 but the lack of a dGPU holds me back.
Something with i5 8250u + MX150/RX 540 would be a perfect combo for me but there is no decent notebook out there, at least i didn't found one. :/

I'll definitely keep an eye out for a nice AMD based notebook...
