### ISSUE TITLE
HPET advice is inconsistent

### ISSUE THREAD

**Issue by Pimpmuckl** [CHEF-KOCH/GamingTweaks#13]
In the myth section: 

> Changing HPET gives you a performance boost. This is incorrect as shown here. Enabling HPET in Bios + leave it untouched under Windows is the best.

Which is simply wrong and outdated.

While the BIOS section has the correct advice:

> Disable High Precision Event Timer (HPET) (not needed after Windows April Update Build 1803 you can check the current status via bcdedit /enum)

**Comment by CHEF-KOCH** [comment]
Thanks. :+1:
