### ISSUE TITLE
Windows 10 20H1 (Codename: Vibranium) - Changes for Gamers

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/GamingTweaks#23]
This is just my personal overview of upcoming Windows 10 20H1 changes, which explicitly addressing gamers (_and of course all others_). I like to keep an eye on specific things which we need to address and fix/correct in the current guidance. That been said, I silently update the topic whenever MS changes something. 

**20H1 (2004) is planned for 17.12.2019 - The rollout (for everyone) will be later.**

- [DNS over HTTPS](https://techcommunity.microsoft.com/t5/Networking-Blog/Windows-will-improve-user-privacy-with-DNS-over-HTTPS/ba-p/1014229)
- GameMode changes and fixes
- [Throttled Search Indexer](http://support.microsoft.com/en-us/help/4526620/updating-to-some-windows-insider-preview-builds-on-devices-with-certai) - Basically a search algorithm which detects heavy disk usage and then [tries to disable specific services](https://www.bleepingcomputer.com/news/microsoft/windows-10-build-19025-with-throttled-search-indexer-out-for-insiders/). Gaming mode needs to run in order to "use" the feature, see [here](https://old.reddit.com/r/Windows10/comments/dxr43c/search_indexer_disk_usage_improvements_in_the/).
- Login performance improvements as well as Narrator performance improvements
- ctfmon.exe crashing and performance improvements
- IPv6 improvements
- Several memory leaks and performance problems with EoAExperiences.exe
- BattlEye improvements (the typically [anti-cheat discussion](http://support.microsoft.com/en-us/help/4526620/updating-to-some-windows-insider-preview-builds-on-devices-with-certai))
- USB 3.0 performance and driver improvements
- [DWM & multiple monitors with different refresh rate problems finally fixed in Windows 10 2004](https://www.reddit.com/r/Windows10/comments/f57tk4/dwm_multiple_monitors_with_different_refresh_rate/)

**Comment by kurtextrem** [comment]
Are the BattlEye improvements only in the fast builds? Can't upgrade to the slow ring build from v1909 final

**Comment by CHEF-KOCH** [comment]
As gamer, you better stay away from Insider Builds (it's not worth it and often creates only problems). 

Yeah, the new changes regarding anti-cheat is triggered by several new implementations (which only affects Insider Builds). But from I know new BattlEye beta builds are already been rolled out. 

If BattlEye blocks an upgrade you should report this, because that's another issue and new.

**Comment by kurtextrem** [comment]
@CHEF-KOCH v1909 apparently is one of the worst in terms of latency. I've also read 20H1 contains additional improvements for Ryzen, so it's worth for me giving it a shot.

I got linked to exactly this: https://support.microsoft.com/en-us/help/4526620/updating-to-some-windows-insider-preview-builds-on-devices-with-certai (which you've linked in the OP) - so I assume BattlEye is again the issue that prevents me from upgrading to the 20H1 slow ring build.

It seems to be a known issue: https://blogs.windows.com/windowsexperience/2019/11/15/announcing-windows-10-insider-preview-build-19025/#hzOJVQ6TmEZhcYqm.97

**Comment by CHEF-KOCH** [comment]
**Latency?!**
Who said that about Windows 10 build 1909 and latency?! According to my own research and [others](https://old.reddit.com/r/Amd/comments/dvoqag/windows_10_1903_vs_1909_update_comparison_on/) Ryzen gained overall 2-3% (WITH latest 1.0.0.4b ABBA BIOS).  The "fastest core prioritization and CCX-aware scheduling" [got fixed in 1903 the same way it got in build 1909](https://old.reddit.com/r/hardware/comments/dbnw8m/windows_10_to_boost_performance_via_favored_cpu/f23u3vz/?context=3) (via KB update). This also fixed some regressions from 1809 (I'm not sure about overall latency, this is difficult to compare due to bugs (older and well-known problematic BIOS updates etc). It's true that the "CPPC hinting" feature was only fully fixed in 1909, but this is also already [proven long time ago](https://www.phoronix.com/scan.php?page=article&item=windows-1903-threadripper&num=2).

[Announcing Windows 10 Insider Preview Build 18362.10019 (19H2)](https://blogs.windows.com/windowsexperience/2019/09/05/announcing-windows-10-insider-preview-build-18362-10019-19h2/#iLv7ct1BBm9KlEQU.97)

> A CPU may have multiple “favored” cores (logical processors of the highest available scheduling class). To provide better performance and reliability, we have implemented a rotation policy that distributes work more fairly among these favored cores.

Was the fix ^^. 

**About BattlEye:**
Okay now I know what you mean, you can just uninstall BattlEye, upgrade and then re-install it (if you want to) which workaround the problem (again that's not MS fault, BattlEye have to fix and adapt the changes MS made in their client, they said the beta client fixes it but apparently they did not fix any "Insider" specific problem). 

Their FAQ is still not updated (yet), the only point when Insider builds are mention is:

> [When starting my game with BattlEye enabled, I get the following error message: “Windows cannot access the specified device, path, or file. You may not have the appropriate permission to access the item.”](https://www.battleye.com/support/faq/).

No, there is no improvement (yet) except problems with BE. I say again that you better stay away from any Insider Builds, it's not worth it. Urgent problems are usually fixed in 1909 via normal "Patch Tuesday" updates.

**Comment by kurtextrem** [comment]
Latency: https://youtu.be/Ljku9FSrXDc

Alright then, thank you for the other info.

**Comment by CHEF-KOCH** [comment]
Yikes, it's the [same dude](https://github.com/CHEF-KOCH/GamingTweaks/commit/fa256b38922c77a36c556d4973e6ccda2504d891) which is known to spread FUD or misinformation. 

Well, I will watch the video tomorrow, I already stopped when I saw "trash" in the title. I expect nothing objective but I check it out, thanks.

**Comment by ImportTaste** [comment]
The BattlEye issue, and pardon if any of this is incorrect but this is how it was explained to me months ago on the Windows Insider Discord, is mainly related to hackers tampering with the OS system files to inject code into games in a way that is not easily detectable (often instructing the OS to spoof checksum validation as well), so the way this is safeguarded is by BattlEye having up-to-date data about each major Windows build - essentially keeping a record of how the system files are _supposed to <ins>behave</ins>_, and throwing a fit if something out-of-the-ordinary is happening.

And, the reality is that Insider builds are far more frequent and tend to rewrite a lot of code, radically changing system file behavior, and thus far it seems like there's no good solution yet, at least for the Fast Ring. In my experience, the Slow Ring is much safer, but with 128GB SSDs being dirt cheap these days, I just fall back to a Stable install on one of those if for some reason the Slow Ring is causing me issues gaming - which has not been often.

**Comment by CHEF-KOCH** [comment]
Yeah, I already said, stay away from beta builds but some people won't listen. 

Some people are simply, pardon me...  ignorant. Beta is beta and there is no point nor benefit in using beta builds, it only causes problems with drivers/software/anti-cheat clients because third-parties need to update and merge/adopt MS changes, they barely can keep up with the Patch Tuesday updates.

One good example is AMD Ryzen Master tool, which not even merged all Windows Build 1903 changes (yet). They need another month to merge the changes for 1903/1009 to display the CCX aware thing correctly. Only HWInfo (beta build) [addressed it](https://www.hwinfo.com/forum/threads/hwinfo-v6-15-4000-beta-released.6035/) .. After months. 

Good stuff simply needs their time, you need to review, test and adopt changes, this is not done overnight.

**Comment by ImportTaste** [comment]
Well, no gaming benefit anyway. The beta builds are extremely significant for Windows Subsystem for Linux users.

**Comment by CHEF-KOCH** [comment]
Yeah, it's like the Windows Sandbox function, cool to have but not perfect, however I think that's off-topic now. 

The overall argument stands, just because MS added a "beta" or test feature into build x, does not mean for gamer that this is automatically useful or "stable". Sandbox as well as [WSL 2](https://medium.com/faun/windows-subsystem-on-linux-wsl-2-first-impressions-96adaf2ebe76) is still flawed. Btw I just realized I never tried to install WSL 2.0 on 19H2, might be [possible](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) even if MS (officially says "nope").  

Anyway there is also the "fair play" argument. I think no one should get a "unfair" benefit just because he installed another Windows 10 build. I know it's not the strongest argument because "tweaking" in general is not entirely fair play too (_unless it's open source and everyone can use and benefit from it_). But downloading and installing Windows 10 builds "officially" requires an MS account (of course you can get the images from unofficial sources) but this basically forces users to use MS own system (which is not really "open" (_new telemetry (maybe) etc._).

**Comment by CHEF-KOCH** [comment]
**Full change log for Windows 10 2004 (20H1) Codename: Vibranium**

- You can reset your PC via Cloud-Download, which means you can reset your machine via local and over remote. You download automatically the latest KB's via WUS and then in-place "upgrade" (reset) the Windows partition.
- Windows "Hello" can now be disabled via settings.exe.
- You can now control the default app behavior after a start or Windows restart.
- Renaming virtual desktops is now possible.
- GPU temp is now shown in the default task manager application.
- Notepad is now a UWP app.
- "Optional Features" are now in a popup window.
- Cursor speed can now be adjusted in the settings.exe.
- Network settings are now improved and enhanced, the status view looks cleaner and introduces more details.
- MS Edge (Chromium) gets NOT integrated by default. MS Edge is still present but whenever you install Chromium it will automatically replace the old one (unless you apply the side-by-side tweak).
- Drivers and feature updates are now been correctly displayed under "optional updates".
- [DirectX 12 Features &  Raytracing Tier 1.1](https://devblogs.microsoft.com/directx/dev-preview-of-new-directx-12-features/), both features are uninteresting for gamers since no application/game will use it until 20H2.
- The calculator app can now be runned in the background (regression from 1909).
- MSIX-Packages do not need the "developer mode workaround". 
- [WSL 2 (Windows Subsystem for Linux) ](https://github.com/microsoft/wsl/)
- Minor corrections
- Xbox Game Bar has a new FPS counter. The transparent background can be enabled.
- Bluetooth-Pairing was fixed.
- Network cameras can now be used with the camera app.
