### ISSUE TITLE
[Needs confirmation] Windows 10 Priority tweaks for better latency

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/GamingTweaks#5]
Some people do believe it fixed Audio lags/stuttering e.g. in PubG or in general reduces the latency. From my knowledge, it is already controlled by the driver but it needs to be tested on AMD/Intel CPU's + Realtek (and maybe other sound chips) to verify if it's really _necessary_ or only placebo.

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile]
"NetworkThrottlingIndex"=dword:00000001
"SystemResponsiveness"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion\Multimedia\SystemProfile\Tasks\Audio]
"Scheduling Category"="High"
"SFIO Priority"="High"
"Latency Sensitive"="True"
"Priority"=dword:00000008
"GPU Priority"=dword:0000001f
"BackgroundPriority"=dword:00000008

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion\Multimedia\SystemProfile\Tasks\Pro Audio]
"Scheduling Category"="High"
"SFIO Priority"="High"
"Latency Sensitive"="True"
"Priority"=dword:00000008
"GPU Priority"=dword:0000001f
"BackgroundPriority"=dword:00000008

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl]
; IRQ 0 = clock of your processor
; IRQ 8 = clock of your motherboard
"IRQ8Priority"=dword:00000001
;"IRQ18Priority"=dword:00000001
"IRQ0Priority"=dword:00000001
"Win32PrioritySeparation"=dword:00000024
```

Source:
http://forum.cakewalk.com/m/tm.aspx?m=3622091&p=4

I comment out IRQ 18, thanks for the hint.

**Comment by CHEF-KOCH** [comment]
I can't confirm that the "latency" tweak has any noticeable impact on the OS or gaming performance. From my experience, the game performance is depending on the engine and how it utilizes your hardware in combination with the driver. There is also no evidence based on benchmarks, a benchmark is a benchmark and has different results almost every time you run it (this is normal) that's why you should run it 3 times to get an avg. (the second time in order to "fill" your ram to ensure everything is maxed out) . I suggest that someone (or me) is doing [this](https://forums.guru3d.com/threads/simple-way-to-trace-dpcs-and-isrs.423884/) to measure the performance impact. 

> It's still not 100% perfect but a huge improvement already for system responsiveness in gaming especially.

I played Resident Evil 2 remake (which has a shitty engine) which affects your CPU the most, even overclocking the GPU doesn't give you any boost unless your CPU is not "blocking" the performance (CPU needs below 80% otherwise you see stuttering).

> This alone can be very beneficial overall, especially for the GPU (nVidia, in particular, does not set MSI mode by default on install because of compatibility issues) and it looks similar to what is described on the CakeWalk forum.

True, but the problem is that I have never seen a game (which I played this and last year) which gives you any boost. I doubt that there is real evidence since no one did benchmarks (except me) and on my system, it doesn't matter if you use MSI mode or not (however some reported that they had a "boost"). Whatever it means because such claims coming without any evidence. 


Ref (no difference):
* https://forums.guru3d.com/threads/windows-line-based-vs-message-signaled-based-interrupts.378044/page-42#post-5626941 (ASMedia USB)
* https://forums.guru3d.com/threads/windows-line-based-vs-message-signaled-based-interrupts.378044/page-41#post-5625033 (GTX 1080 no difference)
* https://forums.guru3d.com/threads/windows-line-based-vs-message-signaled-based-interrupts.378044/page-40#post-5620761 (Intel NIC fixed via driver?)


OS bug:
* https://support.microsoft.com/en-us/help/4480976/windows-10-update-kb4480976

**Comment by Kahana82** [comment]
Definitely it is more about responsiveness (input lag, micro-stutters, sound crapping out and so on) then overall raw performance such as frame rate, at least on my system.
I'm running an Asus X99-m WS board, which is not part of their gaming product line, but is for workstations/servers. Optimizations may differ I suppose.

Also I have a few apps running that could mess things up, like the intel turbo boost app which gives higher priority to the foreground process (background processes getting a too low priority ?)
Then the NZXT's CAM for the AIO cooler which can mess up some systems really badly because of excessive sensor polling and other things it is doing.
And the Logitech G Hub (still in beta) which some users have reported to be less responsive in comparison to LGS.
I need more testing with these ... 

At this point my improvements with MSI_util could be more of an alleviation of symptoms rather then a cure of the cause of what's not going right.

**Comment by CHEF-KOCH** [comment]
That might apply for older systems (I consider an x99 chipset as old) on newer systems the latency is lower because the OS has to check and compute more operations in the same time as shown [here](https://danluu.com/input-lag/). 

It's true that drivers/software like CAM can destroy the performance (latency and FPS) because they are simply badly coded. The simple solution here is not using them (or use alternatives instead) to avoid using any tools in order to _improve_ something (again there is no benchmark or test from any users).

I'm not sure if all the "boost" reports are not placebo, I only believe in the things I can measure and see myself. On my system, there is a difference from 1 fps - I'm not sure about the responsiveness because that depends on several other things e.g. disabling/uninstalling the sound devices might already help more because the OS simply doesn't have to load the driver and the OS has nothing else to process as your device which you only use (that might only prove the point that using as "less" as possible is better).

**Comment by CHEF-KOCH** [comment]
I close this as placebo (until someone provides benchmarks on a professional level).
