### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by PrincessAkira** [CHEF-KOCH/GamingTweaks#51]
In the Document the [https://github.com/CHEF-KOCH/GamingTweaks/blob/master/GPU/nVidia/Readme.md](url) the TweakGuides Link is invalid.

This one is also broken
https://github.com/CHEF-KOCH/GamingTweaks/blob/master/Registry/Readme.md

---------------
Ok i should have fixed it. Commited a fix with some edits.

regards
Akira

**Comment by PrincessAkira** [comment]
This one is also broken
https://github.com/CHEF-KOCH/GamingTweaks/blob/master/Registry/Readme.md

**Comment by PrincessAkira** [comment]
Pull request should have been made according to my VSCode

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/GamingTweaks/commit/f8b21f35af51178713389c561c5852da1c2e0cca
