### ISSUE TITLE
Is safe to use this Mod of Windows 10

### ISSUE THREAD

**Issue by dennyamarojr** [CHEF-KOCH/GamingTweaks#75]
Hi chef,

RECENTLY I decided to try create a version of windows 10 that is superlite and find these mods here
https://m.youtube.com/watch?v=guS5ovEdISQ

Wanna know if is safe to use, in the mod of windows 10 we have gaming edition, so I just want make secure is safe to use. And if is not too much, could you explain how to make a build like the one showed in the video?

**Comment by CHEF-KOCH** [comment]
I do not support any kinds of mods or "gaming editions". 

Which means you will not hear any statements form me on that because I do not waste my time downloading such mods and inspecting them.

You can do everything yourself via [MSMG Toolkit](https://msmgtoolkit.in/). This is the safest way.
