### ISSUE TITLE
How to Integrate Compact + LZX to Windows ISO

### ISSUE THREAD

**Issue by dennyamarojr** [CHEF-KOCH/GamingTweaks#77]
Hi chef, 

I ask you about the ghost spectre isos and you say that never use nodded ISOs, so could you explain how can I integrate The Compact and LZX Algorithm to windows 10 ISO? I'm trying to make my own ISO so I wanna try these lzx algorithm but I don't know how to integrate in the ISO

**Comment by CHEF-KOCH** [comment]
[MSGMToolkit](https://msmgtoolkit.in/) allows you to use (or not use) compression. A video guide is over [here](https://www.youtube.com/watch?v=R6XPff38iSc), the project is also well documented.
