### ISSUE TITLE
How to reduce Windows 10 Installation Size

### ISSUE THREAD

**Issue by dennyamarojr** [CHEF-KOCH/GamingTweaks#78]
Hi CHEF

I'm here to a little help and some little explanation, the Ghost SPECTRE as i show you before and you say that don't recommend I see that the install size of windows is 5.90GB and the normal Windows Size is around 20GB
Could you explain how can I reduce the windows installation size please? And in MSMG Toolkit I saw a tweak to force programa use the latest versions of .NET Framework could provide how van I enable this manually? 

Once again, thanks CHEF.

**Comment by CHEF-KOCH** [comment]
This is not a repository for slipstreaming Windows.
