### ISSUE TITLE
Timeout Detection & Recovery (TDR)

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/GamingTweaks#8]
```sh
Windows Registry Editor Version 5.00

; Off
; Some people say off 3 or 10 are "the best settings".

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrDelay"=dword:00000000
"TdrLevel"=dword:00000000
"TdrDdiDelay"=dword:00000000
"TdrTestMode"=dword:00000000
"TdrDebugMode"=dword:00000000
"TdrLimitTime"=dword:00000000
"TdrLimitCount"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\DCI]
.....
```

I am currently investigating several game related crashes and I got several tips that TDR might have an impact when it comes to "GPU crashes".

### What is TDR?

> TDR stands for Timeout Detection and Recovery. This is a feature of the Windows operating system which detects response problems from a graphics card, and recovers to a functional desktop by resetting the card. If the operating system does not receive a response from a graphics card within a certain amount of time (default is 2 seconds), the operating system resets the graphics card.

> Before TDR existed, problems of this nature would have resulted in a system freeze and required a reboot of the operating system. If TDR is enabled and you see the TDR error message, "Display driver stopped responding and has recovered," this means that the Windows operating system reset the display driver.

### Theory
* Enabling (creating) those toggles helps to fix possible driver related crashes & game crashes.
* "Optimizing" the values results in a better [mining hashrate](https://hashcat.net/wiki/doku.php?id=timeout_patch) 
* Smoother game experience ? (_no evidence_)

### Findings

The official MS documents seems to be outdated. I haven't any of those toggles in my registry, not on AMD, not on Intel or nVidia. However, there are multiple reports that creating the toggles might solve to fix game crashes and driver based crashes. 

### Research:
* https://developer.download.nvidia.com/NsightVisualStudio/2.2/Documentation/UserGuide/HTML/Content/Timeout_Detection_Recovery.htm
* http://msdn.microsoft.com/en-us/library/windows/hardware/ff570088(v=vs.85).aspx (removed)
* https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys
* https://support.passware.com/hc/en-us/articles/115013622267-GPU-driver-timeout-patch
* https://scholars.huji.ac.il/sites/default/files/uriraviv/files/tdrlevelbugfix.pdf
* https://forums.geforce.com/default/topic/872163/windows-10-x64-355-60-stability-at-last-/

### Driver crashes
* https://docs.microsoft.com/en-us/windows-hardware/drivers/display/timeout-detection-and-recovery
* https://community.amd.com/thread/196190
* https://www.pugetsystems.com/labs/hpc/Working-around-TDR-in-Windows-for-a-better-GPU-computing-experience-777/
* https://www.reddit.com/r/nvidia/comments/24rpp5/i_fixed_the_nvidia_driver_has_stopped_responding/

**Comment by Kahana82** [comment]
Wagnard (the author of DDU) has a TDR manipulator, [see his post on the GeForce forums](https://forums.geforce.com/default/topic/550192/geforce-drivers/wagnard-tools-ddu-gmp-tdr-manipulator-new-cpu-core-analyzer-updated-06-08-2019-/post/3846695/#3846695)
Might be worth a look in your investigation.

**Comment by CHEF-KOCH** [comment]
No one provided any interesting information on this subject and every single tool you run has a "normal" margin of error rate which overall brings us to the point that I can't measure or verify if this is placebo or not.

I leave the issue closed until I or Microsoft addressed this "issue". However, Windows 10 is evolving more quickly than any other Windows version before and I think this will be obsolete soon or later anyway because the hardware gets better and might have changed or the noticeable benefit is so low that it's not worth to change something.

Whenever I talk with someone on this subject there are mostly no real benefits, some people only say "it feels smoother" but this could be placebo, or coming from Windows - Keep in mind that Windows often does a lot of background stuff to "optimize" certain task (prefetch, other background tasks/services) and once those tasks are finished you might get a "faster" Windows (in theory). On modern hardware I see almost no benefit anymore anyway because what you "feel" and what actually is coming from apps/software are two different things, combining this fact with the fact that Windows itself might do some background tasks at the time you benchmark your OS makes is really difficult to get something out of it which does apply for all users because the results are in almost every new run different (due to many reasons).

The only effect I can guarantee here is that some games crash with a changed or wrong TDR. However, this only affects old(er) Windows versions.
